language: android
android:
  components:
    - extra-android-support
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-google-m2repository
    - build-tools-22.0.1
    - android-22
    - addon-google_apis-google-19
  licenses:
    - '.+'
env:
  matrix:
    - ANDROID_SDKS=android-19,sysimg-19  ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a
before_install:
  # Install base Android SDK
  - sudo apt-get update -qq
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch > /dev/null; fi
  - wget http://dl.google.com/android/android-sdk_r22.3-linux.tgz
  - tar xzf android-sdk_r22.3-linux.tgz
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  - sudo chmod +x gradlew

  # Gradle
  - wget http://services.gradle.org/distributions/gradle-1.9-bin.zip
  - unzip gradle-1.9-bin.zip
  - export GRADLE_HOME=$PWD/gradle-1.9
  - export PATH=$GRADLE_HOME/bin:$PATH

- echo "LIST SUGGESTED SDK PACKAGES";    android list sdk -e || true
  - echo "LIST AVAILABLE SDK PACKAGES";    android list sdk -a -e || true
  - echo "UPDATE PACKAGES IF REQUIRED";    echo y | android update sdk -u -t platform-tool,tool,\
                                           extra-android-support,extra-google-google_play_services,\
                                           extra-android-m2repository,extra-google-m2repository,\
                                           android-19,sys-img-armeabi-v7a-android-19,\
                                           android-18,sys-img-armeabi-v7a-android-18,\
                                           android-17,sys-img-armeabi-v7a-android-17,\
                                           android-16,sys-img-armeabi-v7a-android-16,\
                                           android-15,sys-img-armeabi-v7a-android-15 || true
  - echo "UPDATE PACKAGES IF POSSIBLE";    echo y | android update sdk -a -u -t ${BUILD_TOOLS},\
                                           android-20,android-21,${SDK_EXTRA_PKGS:-} || true
  - echo "LIST SDK UPDATES BY FILTERS";    android update sdk -u -n -t platform,system-image,\
                                           add-on,extra || true



 # Create and start emulator
  #- echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  #- emulator -avd test -no-skin -no-audio -no-window &
script:
  - gradle clean check


